"""Report-only TeX equation canonical text normalizer design audit.

This helper compares conservative normalizer profiles for TeX equation text
against PyMuPDF-generated canonical Markdown text. It is a design audit only:
it does not create source spans, interpret equations, route parsers, mutate
SQLite, reindex, reembed, write canonical parsed artifacts, or change answer
behavior.
"""

from __future__ import annotations

from argparse import ArgumentParser
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
import re
from typing import Any

from knowledge_hub.papers.tex_equation_canonical_alignment_diagnostic_audit import (
    TEX_EQUATION_CANONICAL_ALIGNMENT_DIAGNOSTIC_AUDIT_SCHEMA_ID,
)
from knowledge_hub.papers.tex_equation_normalization_bridge_audit import (
    DEFAULT_TEX_EQUATION_DIAGNOSTIC_REPORT,
)
from knowledge_hub.papers.tex_structure_candidate_alignment_audit import DEFAULT_PARSED_ROOT


TEX_EQUATION_CANONICAL_TEXT_NORMALIZER_DESIGN_SCHEMA_ID = (
    "knowledge-hub.paper.tex-equation-canonical-text-normalizer-design.v1"
)

_WHITESPACE_RE = re.compile(r"\s+")
_GROUP_COMMAND_RE = re.compile(
    r"\\(?:mathrm|mathtt|textrm|textbf|textit|text|operatorname\*?|mathbf|mathit|mathbbm|mathlarger)\s*\{([^{}]*)\}"
)
_FRAC_RE = re.compile(r"\\frac\s*\{([^{}]*)\}\s*\{([^{}]*)\}")
_SQRT_RE = re.compile(r"\\sqrt\s*\{([^{}]*)\}")
_LABEL_RE = re.compile(r"\\label\s*\{[^{}]*\}")
_COMMAND_RE = re.compile(r"\\([A-Za-z]+)\*?")
_CANONICAL_TOKEN_RE = re.compile(r"[A-Za-z]+[A-Za-z0-9]*|[0-9]+(?:\.[0-9]+)?")
_MATH_FRAGMENT_RE = re.compile(r"[A-Za-z]+(?:[A-Za-z0-9]|[_^{}])*|[0-9]+(?:\.[0-9]+)?")
_STOP_TOKENS = {
    "begin",
    "end",
    "equation",
    "align",
    "array",
    "cases",
    "text",
    "mathrm",
    "mathtt",
    "textrm",
    "textbf",
    "operatorname",
    "mathlarger",
    "mathbbm",
    "scriptsize",
    "displaystyle",
    "left",
    "right",
    "qquad",
    "quad",
    "cdot",
    "sum",
    "frac",
    "sqrt",
    "where",
    "label",
    "eq",
    "and",
    "assuming",
    "by",
    "expectation",
    "independence",
    "indepedence",
    "linearity",
    "of",
}


@dataclass(frozen=True)
class _Token:
    text: str
    start: int
    end: int


@dataclass(frozen=True)
class _Profile:
    name: str
    description: str
    proposed_rules: tuple[str, ...]


_PROFILES = (
    _Profile(
        name="ordered_bridge_terms_v1",
        description="Use macro-elided ordered TeX terms as generated by the first bridge audit.",
        proposed_rules=(
            "latex_text_macro_elision",
            "latex_label_elision",
            "fraction_and_sqrt_token_exposure",
            "unicode_math_symbol_name_bridge",
            "ordered_anchor_token_window",
        ),
    ),
    _Profile(
        name="canonical_math_compaction_v1",
        description="Compact TeX subscript/superscript fragments into canonical Markdown-like alphanumeric math tokens.",
        proposed_rules=(
            "latex_text_macro_elision",
            "latex_label_elision",
            "fraction_and_sqrt_token_exposure",
            "subscript_superscript_alnum_compaction",
            "unicode_math_symbol_name_bridge",
            "ordered_anchor_token_window",
        ),
    ),
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _read_json(path: str | Path | None) -> dict[str, Any]:
    if not path:
        return {}
    try:
        payload = json.loads(Path(str(path)).expanduser().read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def _read_text(path: str | Path | None) -> str:
    if not path:
        return ""
    try:
        return Path(str(path)).expanduser().read_text(encoding="utf-8")
    except Exception:
        return ""


def _clean_text(value: Any) -> str:
    return _WHITESPACE_RE.sub(" ", str(value or "").strip())


def _strip_latex_wrappers(value: str) -> str:
    text = _LABEL_RE.sub(" ", value)
    previous = ""
    while previous != text:
        previous = text
        text = _GROUP_COMMAND_RE.sub(r" \1 ", text)
    text = _FRAC_RE.sub(r" \1 \2 ", text)
    text = _SQRT_RE.sub(r" sqrt \1 ", text)
    text = _COMMAND_RE.sub(r" \1 ", text)
    return text.replace("\\\\", " ")


def _normalize_token(token: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", token).casefold()


def _add_term(terms: list[str], seen: set[str], value: str) -> None:
    compact = re.sub(r"[^A-Za-z0-9]", "", value)
    normalized = _normalize_token(compact)
    if len(normalized) < 2 or normalized in _STOP_TOKENS or normalized in seen:
        return
    seen.add(normalized)
    terms.append(compact)


def _ordered_bridge_terms(candidate_text: str) -> list[str]:
    text = _strip_latex_wrappers(candidate_text)
    text = re.sub(r"[{}&_^]", " ", text)
    text = re.sub(r"[\[\](),=+*/<>|:;.-]+", " ", text)
    terms: list[str] = []
    seen: set[str] = set()
    for token in _CANONICAL_TOKEN_RE.findall(text):
        _add_term(terms, seen, token)
    return terms[:32]


def _canonical_math_compaction_terms(candidate_text: str) -> list[str]:
    text = _strip_latex_wrappers(candidate_text)
    terms: list[str] = []
    seen: set[str] = set()
    for token in _MATH_FRAGMENT_RE.findall(text):
        _add_term(terms, seen, token)
    return terms[:32]


def _profile_terms(profile_name: str, candidate_text: str) -> list[str]:
    if profile_name == "canonical_math_compaction_v1":
        return _canonical_math_compaction_terms(candidate_text)
    return _ordered_bridge_terms(candidate_text)


def _canonical_bridge_text(value: str) -> str:
    text = value.replace("ﬁ", "fi").replace("ﬂ", "fl")
    text = text.replace("×", " x ").replace("∗", " * ")
    text = text.replace("−", " - ").replace("–", " - ").replace("—", " - ")
    text = text.replace("√", " sqrt ")
    text = text.replace("∆", " Delta ").replace("Δ", " Delta ")
    text = text.replace("Φ", " Phi ").replace("φ", " phi ")
    text = text.replace("Θ", " Theta ").replace("θ", " theta ")
    text = text.replace("∈", " in ").replace("·", " cdot ")
    return text


def _canonical_tokens(document_text: str) -> list[_Token]:
    return [
        _Token(match.group(0), match.start(), match.end())
        for match in _CANONICAL_TOKEN_RE.finditer(_canonical_bridge_text(document_text))
    ]


def _matches_anchor(token: str, anchor: str) -> bool:
    token_norm = _normalize_token(token)
    anchor_norm = _normalize_token(anchor)
    if token_norm == anchor_norm:
        return True
    if len(anchor_norm) < 2:
        return False
    return token_norm.startswith(anchor_norm) or anchor_norm in token_norm


def _anchor_match_end_index(
    canonical_tokens: list[_Token],
    start_index: int,
    anchor: str,
    *,
    max_span_tokens: int = 4,
) -> int | None:
    if _matches_anchor(canonical_tokens[start_index].text, anchor):
        return start_index
    anchor_norm = _normalize_token(anchor)
    if len(anchor_norm) < 3 and not any(char.isupper() or char.isdigit() for char in anchor):
        return None
    compact = ""
    span_stop = min(len(canonical_tokens), start_index + max_span_tokens)
    for end_index in range(start_index, span_stop):
        compact += _normalize_token(canonical_tokens[end_index].text)
        if compact == anchor_norm or compact.startswith(anchor_norm):
            return end_index
        if len(compact) >= len(anchor_norm):
            break
    return None


def _ordered_windows(
    anchors: list[str],
    canonical_tokens: list[_Token],
    *,
    max_gap_tokens: int = 50,
) -> list[tuple[int, int]]:
    if len(anchors) < 2:
        return []
    windows: list[tuple[int, int]] = []
    for start_index, token in enumerate(canonical_tokens):
        first_end = _anchor_match_end_index(canonical_tokens, start_index, anchors[0])
        if first_end is None:
            continue
        current_index = first_end
        matched = 1
        for anchor in anchors[1:]:
            next_index = None
            search_stop = min(len(canonical_tokens), current_index + max_gap_tokens + 1)
            for candidate_index in range(current_index + 1, search_stop):
                match_end = _anchor_match_end_index(canonical_tokens, candidate_index, anchor)
                if match_end is not None:
                    next_index = match_end
                    break
            if next_index is None:
                break
            current_index = next_index
            matched += 1
        if matched == len(anchors):
            windows.append((start_index, current_index))
    return windows


def _status(
    *,
    candidate_text: str,
    canonical_available: bool,
    terms: list[str],
    window_count: int,
) -> tuple[str, float]:
    if not candidate_text:
        return "empty_equation_text", 1.0
    if not canonical_available:
        return "canonical_document_missing", 1.0
    if len(terms) < 2:
        return "insufficient_normalized_terms", 0.15
    if window_count == 1:
        return "unique_normalized_window_candidate_only", 0.7
    if window_count > 1:
        return "ambiguous_normalized_window_candidate_only", 0.35
    return "normalized_window_not_found", 0.1


def _profile_result(
    profile: _Profile,
    *,
    candidate_text: str,
    canonical_available: bool,
    canonical_tokens: list[_Token],
) -> dict[str, Any]:
    terms = _profile_terms(profile.name, candidate_text)
    windows = _ordered_windows(terms, canonical_tokens) if canonical_available else []
    status, confidence = _status(
        candidate_text=candidate_text,
        canonical_available=canonical_available,
        terms=terms,
        window_count=len(windows),
    )
    return {
        "profile_name": profile.name,
        "description": profile.description,
        "proposed_rules": list(profile.proposed_rules),
        "normalized_terms": terms,
        "normalized_term_count": len(terms),
        "window_count": len(windows),
        "status": status,
        "confidence": confidence,
    }


def _best_profile(profile_results: list[dict[str, Any]]) -> dict[str, Any]:
    priority = {
        "unique_normalized_window_candidate_only": 0,
        "ambiguous_normalized_window_candidate_only": 1,
        "normalized_window_not_found": 2,
        "insufficient_normalized_terms": 3,
        "empty_equation_text": 4,
        "canonical_document_missing": 5,
    }
    return min(
        profile_results,
        key=lambda result: (
            priority.get(str(result.get("status") or ""), 99),
            -int(result.get("normalized_term_count") or 0),
        ),
    )


def _recommended_action(status: str) -> str:
    if status == "unique_normalized_window_candidate_only":
        return "keep_as_normalizer_design_candidate_no_source_span"
    if status == "ambiguous_normalized_window_candidate_only":
        return "requires_line_local_or_equation_number_anchor_before_source_span"
    if status == "normalized_window_not_found":
        return "requires_canonical_equation_rendering_or_pdf_layout_anchor"
    if status == "insufficient_normalized_terms":
        return "requires_non_equation_label_filter_or_manual_design_review"
    if status == "empty_equation_text":
        return "hold_out_empty_equation_environment"
    return "blocked"


def _paper_document_path(parsed_root: Path, paper_id: str) -> Path:
    return parsed_root / paper_id / "document.md"


def _row(
    index: int,
    diagnostic_row: dict[str, Any],
    *,
    parsed_root: Path,
    document_cache: dict[str, str],
) -> dict[str, Any]:
    paper_id = str(diagnostic_row.get("paper_id") or "")
    document_path = _paper_document_path(parsed_root, paper_id)
    document_key = str(document_path)
    if document_key not in document_cache:
        document_cache[document_key] = _read_text(document_path)
    document_text = document_cache[document_key]
    candidate_text = _clean_text(diagnostic_row.get("candidate_text"))
    canonical_tokens = _canonical_tokens(document_text)
    profile_results = [
        _profile_result(
            profile,
            candidate_text=candidate_text,
            canonical_available=bool(document_text),
            canonical_tokens=canonical_tokens,
        )
        for profile in _PROFILES
    ]
    best = _best_profile(profile_results)
    status = str(best.get("status") or "")
    blockers = list(
        dict.fromkeys(
            [
                "tex_equation_canonical_text_normalizer_design_only",
                "normalizer_design_does_not_create_source_spans",
                "equation_semantics_not_interpreted",
                "equation_region_link_unverified",
                "runtime_promotion_disabled_for_tranche",
                "strict_promotion_requires_later_explicit_tranche",
                "canonical_generated_markdown_offsets_are_not_original_pdf_offsets",
                "tex_offsets_are_not_canonical_source_spans",
                "normalized_windows_are_diagnostic_not_provenance",
                *[str(item) for item in list(diagnostic_row.get("strict_blockers") or [])],
            ]
        )
    )
    return {
        "design_id": f"tex-equation-canonical-text-normalizer-design:{index:04d}",
        "source_diagnostic_id": str(diagnostic_row.get("diagnostic_id") or ""),
        "source_candidate_id": str(diagnostic_row.get("source_candidate_id") or ""),
        "paper_id": paper_id,
        "candidate_type": "tex_equation_canonical_text_normalizer_design",
        "source_parser": "arxiv_tex+pymupdf_alignment",
        "source_file": str(diagnostic_row.get("source_file") or ""),
        "equation_environment": str(diagnostic_row.get("equation_environment") or ""),
        "candidate_text": candidate_text,
        "canonical_document_path": document_key,
        "canonical_document_available": bool(document_text),
        "profile_results": profile_results,
        "recommended_profile": str(best.get("profile_name") or ""),
        "recommended_status": status,
        "recommended_action": _recommended_action(status),
        "sourceContentHash": str(diagnostic_row.get("sourceContentHash") or ""),
        "chars_start": None,
        "chars_end": None,
        "page": None,
        "source_span_created": False,
        "equation_semantics_interpreted": False,
        "equation_region_verified": False,
        "evidence_tier": "tex_equation_canonical_text_normalizer_design_only",
        "strict_eligible": False,
        "citation_grade": False,
        "runtime_evidence": False,
        "strict_blockers": blockers,
        "non_strict_reason": [
            "normalizer_design_rows_are_not_evidence",
            "normalized_windows_do_not_create_source_spans",
            "later_explicit_promotion_tranche_required",
        ],
    }


def _profile_summary(rows: list[dict[str, Any]]) -> dict[str, Any]:
    summary: dict[str, Any] = {}
    for profile in _PROFILES:
        statuses: Counter[str] = Counter()
        for row in rows:
            for result in list(row.get("profile_results") or []):
                if str(result.get("profile_name") or "") == profile.name:
                    statuses[str(result.get("status") or "")] += 1
        summary[profile.name] = dict(statuses)
    return summary


def _counts(rows: list[dict[str, Any]], schema_violations: list[str]) -> dict[str, Any]:
    by_status = Counter(str(row.get("recommended_status") or "") for row in rows)
    by_paper = Counter(str(row.get("paper_id") or "") for row in rows)
    return {
        "equationDiagnosticRows": len(rows),
        "textBearingEquationRows": sum(1 for row in rows if row.get("candidate_text")),
        "emptyEquationTextRows": sum(1 for row in rows if not row.get("candidate_text")),
        "normalizerProfileCount": len(_PROFILES),
        "bestUniqueWindowRows": int(by_status.get("unique_normalized_window_candidate_only", 0)),
        "bestAmbiguousWindowRows": int(by_status.get("ambiguous_normalized_window_candidate_only", 0)),
        "bestFailedWindowRows": int(by_status.get("normalized_window_not_found", 0)),
        "sourceSpanCreatedRows": 0,
        "strictEligibleRows": 0,
        "citationGradeRows": 0,
        "runtimeEvidenceRows": 0,
        "schemaViolationCount": len(schema_violations),
        "byPaper": dict(by_paper),
        "byRecommendedStatus": dict(by_status),
        "byProfileStatus": _profile_summary(rows),
    }


def build_tex_equation_canonical_text_normalizer_design(
    *,
    diagnostic_report: str | Path = DEFAULT_TEX_EQUATION_DIAGNOSTIC_REPORT,
    parsed_root: str | Path = DEFAULT_PARSED_ROOT,
    paper_ids: list[str] | None = None,
) -> dict[str, Any]:
    input_path = Path(str(diagnostic_report)).expanduser()
    parsed_root_path = Path(str(parsed_root)).expanduser()
    payload = _read_json(input_path)
    requested = [str(item).strip() for item in (paper_ids or []) if str(item).strip()]
    allowed = set(requested)
    schema = str(payload.get("schema") or "")
    schema_violations = [] if schema == TEX_EQUATION_CANONICAL_ALIGNMENT_DIAGNOSTIC_AUDIT_SCHEMA_ID else [
        "tex_equation_canonical_alignment_diagnostic_report_schema_mismatch"
    ]
    source_rows = [
        dict(row)
        for row in list(payload.get("rows") or [])
        if isinstance(row, dict) and (not allowed or str(row.get("paper_id") or "") in allowed)
    ]
    document_cache: dict[str, str] = {}
    rows = [
        _row(index + 1, row, parsed_root=parsed_root_path, document_cache=document_cache)
        for index, row in enumerate(source_rows)
        if not schema_violations
    ]
    counts = _counts(rows, schema_violations)
    return {
        "schema": TEX_EQUATION_CANONICAL_TEXT_NORMALIZER_DESIGN_SCHEMA_ID,
        "status": "ok" if rows and not schema_violations else "blocked",
        "generatedAt": _now(),
        "input": {
            "diagnosticReportPath": str(input_path),
            "diagnosticReportSchema": schema,
            "parsedRoot": str(parsed_root_path),
            "paperIds": requested,
        },
        "counts": counts,
        "gate": {
            "designReady": bool(rows) and not schema_violations,
            "sourceSpanCreationReady": False,
            "strictEvidenceReady": False,
            "parserRoutingReady": False,
            "answerIntegrationReady": False,
            "runtimePromotionAllowed": False,
            "decision": "equation_canonical_text_normalizer_design_recorded"
            if rows and not schema_violations
            else "blocked",
            "schemaViolations": schema_violations,
            "recommendedNextTranche": "tex_equation_line_local_anchor_audit",
        },
        "policy": {
            "reportOnly": True,
            "designOnly": True,
            "strictEvidenceCreated": False,
            "runtimePromotionAllowed": False,
            "parserRoutingChanged": False,
            "canonicalParsedArtifactsWritten": False,
            "databaseMutation": False,
            "vaultScan": False,
            "reindexOrReembed": False,
            "answerIntegrationChanged": False,
            "equationInterpretationAllowed": False,
        },
        "profiles": [
            {
                "profile_name": profile.name,
                "description": profile.description,
                "proposed_rules": list(profile.proposed_rules),
            }
            for profile in _PROFILES
        ],
        "warnings": [
            "normalizer_design_windows_do_not_create_source_spans",
            "equation_semantics_are_not_interpreted",
            "canonical_generated_markdown_offsets_are_not_original_pdf_offsets",
            "equation_candidates_remain_non_strict_until_an_explicit_promotion_tranche",
        ],
        "rows": rows,
    }


def _summary_payload(report: dict[str, Any]) -> dict[str, Any]:
    return {
        key: report[key]
        for key in ("schema", "status", "generatedAt", "input", "counts", "gate", "policy", "profiles", "warnings")
        if key in report
    }


def render_tex_equation_canonical_text_normalizer_design_markdown(report: dict[str, Any]) -> str:
    counts = dict(report.get("counts") or {})
    gate = dict(report.get("gate") or {})
    lines = [
        "# TeX Equation Canonical Text Normalizer Design",
        "",
        f"- Status: `{report.get('status', '')}`",
        f"- Decision: `{gate.get('decision', '')}`",
        f"- Equation diagnostic rows: `{int(counts.get('equationDiagnosticRows') or 0)}`",
        f"- Text-bearing equation rows: `{int(counts.get('textBearingEquationRows') or 0)}`",
        f"- Normalizer profiles: `{int(counts.get('normalizerProfileCount') or 0)}`",
        f"- Best unique-window rows: `{int(counts.get('bestUniqueWindowRows') or 0)}`",
        f"- Best ambiguous-window rows: `{int(counts.get('bestAmbiguousWindowRows') or 0)}`",
        f"- Best failed-window rows: `{int(counts.get('bestFailedWindowRows') or 0)}`",
        f"- Source spans created: `{int(counts.get('sourceSpanCreatedRows') or 0)}`",
        f"- Strict eligible rows: `{int(counts.get('strictEligibleRows') or 0)}`",
        "",
        "## Policy",
        "",
        "This report is a normalizer design audit only. Normalized windows are not source spans or evidence.",
        "",
        "## Counts",
        "",
        f"- By paper: `{json.dumps(counts.get('byPaper') or {}, ensure_ascii=False, sort_keys=True)}`",
        f"- By recommended status: `{json.dumps(counts.get('byRecommendedStatus') or {}, ensure_ascii=False, sort_keys=True)}`",
        f"- By profile status: `{json.dumps(counts.get('byProfileStatus') or {}, ensure_ascii=False, sort_keys=True)}`",
        "",
    ]
    return "\n".join(lines)


def write_tex_equation_canonical_text_normalizer_design_reports(
    report: dict[str, Any],
    output_dir: str | Path,
) -> dict[str, str]:
    root = Path(str(output_dir)).expanduser()
    root.mkdir(parents=True, exist_ok=True)
    report_path = root / "tex-equation-canonical-text-normalizer-design-report.json"
    summary_path = root / "tex-equation-canonical-text-normalizer-design-summary.json"
    markdown_path = root / "tex-equation-canonical-text-normalizer-design.md"
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    summary_path.write_text(json.dumps(_summary_payload(report), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(render_tex_equation_canonical_text_normalizer_design_markdown(report), encoding="utf-8")
    return {"report": str(report_path), "summary": str(summary_path), "markdown": str(markdown_path)}


def main(argv: list[str] | None = None) -> int:
    parser = ArgumentParser(description="Generate a report-only TeX equation canonical text normalizer design audit.")
    parser.add_argument("--diagnostic-report", default=str(DEFAULT_TEX_EQUATION_DIAGNOSTIC_REPORT))
    parser.add_argument("--parsed-root", default=str(DEFAULT_PARSED_ROOT))
    parser.add_argument("--paper-id", action="append", default=[], help="Filter to a paper id; can be repeated.")
    parser.add_argument("--output-dir", required=True, help="Directory for local JSON/Markdown reports.")
    parser.add_argument("--json", action="store_true", help="Print summary payload as JSON.")
    args = parser.parse_args(argv)

    report = build_tex_equation_canonical_text_normalizer_design(
        diagnostic_report=args.diagnostic_report,
        parsed_root=args.parsed_root,
        paper_ids=args.paper_id or None,
    )
    paths = write_tex_equation_canonical_text_normalizer_design_reports(report, args.output_dir)
    summary = _summary_payload(report)
    summary["reportPaths"] = paths
    if args.json:
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())


__all__ = [
    "TEX_EQUATION_CANONICAL_TEXT_NORMALIZER_DESIGN_SCHEMA_ID",
    "build_tex_equation_canonical_text_normalizer_design",
    "render_tex_equation_canonical_text_normalizer_design_markdown",
    "write_tex_equation_canonical_text_normalizer_design_reports",
]
