"""Centralized JSON schema validation helpers.

This module keeps CLI/Service outputs contract-safe without forcing validation
into every call site. It maps contract IDs to docs/schemas/*.json and returns
non-blocking diagnostics when schema files are missing.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any
import json
from jsonschema import Draft202012Validator

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_ROOT = PROJECT_ROOT / "docs" / "schemas"

SCHEMA_NAME_BY_ID = {
    "knowledge-hub.document-memory.build.result.v1": "document-memory-build-result.v1.json",
    "knowledge-hub.document-memory.card.result.v1": "document-memory-card-result.v1.json",
    "knowledge-hub.document-memory.search.result.v1": "document-memory-search-result.v1.json",
    "knowledge-hub.memory-route.result.v1": "memory-route-result.v1.json",
    "knowledge-hub.document-memory.eval.prepare.result.v1": "document-memory-eval-prepare-result.v1.json",
    "knowledge-hub.document-memory.eval.report.v1": "document-memory-eval-report.v1.json",
    "knowledge-hub.memory-router.eval.report.v1": "memory-router-eval-report.v1.json",
    "knowledge-hub.ask-v2.eval.report.v1": "ask-v2-eval-report.v1.json",
    "knowledge-hub.claim-synthesis.eval.prepare.result.v1": "claim-synthesis-eval-prepare-result.v1.json",
    "knowledge-hub.claim-synthesis.eval.report.v1": "claim-synthesis-eval-report.v1.json",
    "knowledge-hub.paper-summary.build.result.v1": "paper-summary-build-result.v1.json",
    "knowledge-hub.paper-summary.card.result.v1": "paper-summary-card-result.v1.json",
    "knowledge-hub.paper-summary.eval.prepare.result.v1": "paper-summary-eval-prepare-result.v1.json",
    "knowledge-hub.paper.public.summary.v1": "paper-public-summary-result.v1.json",
    "knowledge-hub.paper.public.evidence.v1": "paper-public-evidence-result.v1.json",
    "knowledge-hub.paper.public.memory.v1": "paper-public-memory-result.v1.json",
    "knowledge-hub.paper.public.related.v1": "paper-public-related-result.v1.json",
    "knowledge-hub.paper.source-alias-normalization-case.v1": "paper-source-alias-normalization-case.v1.json",
    "knowledge-hub.paper.source-alias-normalization-report.v1": "paper-source-alias-normalization-report.v1.json",
    "knowledge-hub.paper.text-evidence-rc-text-only-scope-gate.v1": "paper-text-evidence-rc-text-only-scope-gate.v1.json",
    "knowledge-hub.paper.text-span-artifact-candidate.v1": "paper-text-span-artifact-candidate.v1.json",
    "knowledge-hub.paper.text-section-paragraph-span-artifacts-report.v1": "paper-text-section-paragraph-span-artifacts-report.v1.json",
    "knowledge-hub.paper.table-text-artifact-candidate.v1": "paper-table-text-artifact-candidate.v1.json",
    "knowledge-hub.paper.text-table-caption-candidate-artifacts-report.v1": "paper-text-table-caption-candidate-artifacts-report.v1.json",
    "knowledge-hub.paper.figure-caption-artifact-candidate.v1": "paper-figure-caption-artifact-candidate.v1.json",
    "knowledge-hub.paper.figure-caption-artifact-vertical-slice-report.v1": "paper-figure-caption-artifact-vertical-slice-report.v1.json",
    "knowledge-hub.paper.figure-caption-text-qa-readback.v1": "paper-figure-caption-text-qa-readback.v1.json",
    "knowledge-hub.paper.figure-caption-text-qa-readback-report.v1": "paper-figure-caption-text-qa-readback-report.v1.json",
    "knowledge-hub.paper.evidence-chunk-answer-preview.result.v1": "paper-evidence-chunk-answer-preview-result.v1.json",
    "knowledge-hub.paper.extraction-report.v1": "paper-extraction-report-result.v1.json",
    "knowledge-hub.paper.parsed-materialization.result.v1": "paper-parsed-materialization-result.v1.json",
    "knowledge-hub.paper.parsed-artifact-coverage-audit.v1": "paper-parsed-artifact-coverage-audit.v1.json",
    "knowledge-hub.paper.parsed-artifact-parser-quality-degradation-audit.v1": "paper-parsed-artifact-parser-quality-degradation-audit.v1.json",
    "knowledge-hub.paper.parsed-artifact-pymupdf-quality-repair-design.v1": "paper-parsed-artifact-pymupdf-quality-repair-design.v1.json",
    "knowledge-hub.paper.parsed-artifact-pymupdf-quality-repair-executor-dry-run.v1": "paper-parsed-artifact-pymupdf-quality-repair-executor-dry-run.v1.json",
    "knowledge-hub.paper.parsed-artifact-pymupdf-quality-repair-sidecar-oracle-comparison.v1": "paper-parsed-artifact-pymupdf-quality-repair-sidecar-oracle-comparison.v1.json",
    "knowledge-hub.paper.parsed-artifact-pymupdf-quality-repair-sidecar-oracle-candidate-pack-design.v1": "paper-parsed-artifact-pymupdf-quality-repair-sidecar-oracle-candidate-pack-design.v1.json",
    "knowledge-hub.paper.parsed-artifact-pymupdf-quality-repair-sidecar-oracle-candidate-pack-executor-dry-run.v1": "paper-parsed-artifact-pymupdf-quality-repair-sidecar-oracle-candidate-pack-executor-dry-run.v1.json",
    "knowledge-hub.paper.parsed-artifact-pymupdf-quality-repair-sidecar-oracle-pack.v1": "paper-parsed-artifact-pymupdf-quality-repair-sidecar-oracle-pack.v1.json",
    "knowledge-hub.paper.parsed-artifact-coverage-batch-report.v1": "paper-parsed-artifact-coverage-batch-report.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-blocker-report.v1": "paper-parsed-artifact-source-blocker-report.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-missing-resolution-plan.v1": "paper-parsed-artifact-source-missing-resolution-plan.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-recovery-feasibility.v1": "paper-parsed-artifact-source-recovery-feasibility.v1.json",
    "knowledge-hub.paper.parsed-artifact-manual-lookup-source-recovery-plan.v1": "paper-parsed-artifact-manual-lookup-source-recovery-plan.v1.json",
    "knowledge-hub.paper.parsed-artifact-manual-lookup-source-recovery-review-pack.v1": "paper-parsed-artifact-manual-lookup-source-recovery-review-pack.v1.json",
    "knowledge-hub.paper.parsed-artifact-manual-lookup-source-recovery-decision-file-draft.v1": "paper-parsed-artifact-manual-lookup-source-recovery-decision-file-draft.v1.json",
    "knowledge-hub.paper.parsed-artifact-manual-lookup-source-recovery-decision-file-validation.v1": "paper-parsed-artifact-manual-lookup-source-recovery-decision-file-validation.v1.json",
    "knowledge-hub.paper.parsed-artifact-manual-lookup-source-recovery-decision-file-human-review.v1": "paper-parsed-artifact-manual-lookup-source-recovery-decision-file-human-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-manual-lookup-source-recovery-operator-decision-packet.v1": "paper-parsed-artifact-manual-lookup-source-recovery-operator-decision-packet.v1.json",
    "knowledge-hub.paper.parsed-artifact-manual-lookup-source-recovery-decision-file-apply-dry-run.v1": "paper-parsed-artifact-manual-lookup-source-recovery-decision-file-apply-dry-run.v1.json",
    "knowledge-hub.paper.parsed-artifact-manual-lookup-source-recovery-decision-file-apply.v1": "paper-parsed-artifact-manual-lookup-source-recovery-decision-file-apply.v1.json",
    "knowledge-hub.paper.parsed-artifact-oversized-pdf-materialization-dry-run.v1": "paper-parsed-artifact-oversized-pdf-materialization-dry-run.v1.json",
    "knowledge-hub.paper.parsed-artifact-oversized-pdf-materialization-apply.v1": "paper-parsed-artifact-oversized-pdf-materialization-apply.v1.json",
    "knowledge-hub.paper.parsed-artifact-arxiv-source-recovery.v1": "paper-parsed-artifact-arxiv-source-recovery.v1.json",
    "knowledge-hub.paper.parsed-artifact-url-source-recovery.v1": "paper-parsed-artifact-url-source-recovery.v1.json",
    "knowledge-hub.paper.layout-parser-pilot.result.v1": "paper-layout-parser-pilot-result.v1.json",
    "knowledge-hub.paper.arxiv-source-tex-availability-audit.v1": "paper-arxiv-source-tex-availability-audit.v1.json",
    "knowledge-hub.paper.tex-structure-candidate-alignment-audit.v1": "paper-tex-structure-candidate-alignment-audit.v1.json",
    "knowledge-hub.paper.tex-sectionspan-candidate-report.v1": "paper-tex-sectionspan-candidate-report.v1.json",
    "knowledge-hub.paper.tex-figure-caption-candidate-report.v1": "paper-tex-figure-caption-candidate-report.v1.json",
    "knowledge-hub.paper.tex-equation-quote-candidate-report.v1": "paper-tex-equation-quote-candidate-report.v1.json",
    "knowledge-hub.paper.tex-equation-canonical-alignment-diagnostic-audit.v1": "paper-tex-equation-canonical-alignment-diagnostic-audit.v1.json",
    "knowledge-hub.paper.tex-equation-normalization-bridge-audit.v1": "paper-tex-equation-normalization-bridge-audit.v1.json",
    "knowledge-hub.paper.tex-equation-canonical-text-normalizer-design.v1": "paper-tex-equation-canonical-text-normalizer-design.v1.json",
    "knowledge-hub.paper.tex-equation-line-local-anchor-audit.v1": "paper-tex-equation-line-local-anchor-audit.v1.json",
    "knowledge-hub.paper.tex-equation-pdf-region-anchor-audit.v1": "paper-tex-equation-pdf-region-anchor-audit.v1.json",
    "knowledge-hub.paper.parsed-artifact-structured-evidence-execution-plan.v1": "paper-parsed-artifact-structured-evidence-execution-plan.v1.json",
    "knowledge-hub.paper.parsed-artifact-structured-evidence-write-target-contract-audit.v1": "paper-parsed-artifact-structured-evidence-write-target-contract-audit.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-candidate-store-contract.v1": "paper-parsed-artifact-source-span-candidate-store-contract.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-candidate-record.v1": "paper-parsed-artifact-source-span-candidate-record.v1.json",
    "knowledge-hub.paper.structured-evidence-candidate-record.v1": "paper-structured-evidence-candidate-record.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-candidate-executor.v1": "paper-parsed-artifact-source-span-candidate-executor.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-candidate-readback-review.v1": "paper-parsed-artifact-source-span-candidate-readback-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-candidate-promotion-policy-gate.v1": "paper-parsed-artifact-source-span-candidate-promotion-policy-gate.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-promotion-executor-dry-run.v1": "paper-parsed-artifact-source-span-promotion-executor-dry-run.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-store-contract.v1": "paper-parsed-artifact-source-span-store-contract.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-record.v1": "paper-parsed-artifact-source-span-record.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-promotion-executor-apply.v1": "paper-parsed-artifact-source-span-promotion-executor-apply.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-promotion-readback-review.v1": "paper-parsed-artifact-source-span-promotion-readback-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-strict-evidence-policy-gate-v2-typed.v1": "paper-parsed-artifact-source-span-strict-evidence-policy-gate-v2-typed.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-original-source-offset-authority-design.v1": "paper-parsed-artifact-source-span-original-source-offset-authority-design.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-strict-evidence-design-review.v1": "paper-parsed-artifact-source-span-strict-evidence-design-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-text-match-disambiguation-design.v1": "paper-parsed-artifact-source-span-text-match-disambiguation-design.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-strict-evidence-design-review-reconciliation.v1": "paper-parsed-artifact-source-span-strict-evidence-design-review-reconciliation.v1.json",
    "knowledge-hub.paper.parsed-artifact-source-span-strict-evidence-design-packet-review.v1": "paper-parsed-artifact-source-span-strict-evidence-design-packet-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-strict-evidence-record-contract.v1": "paper-parsed-artifact-strict-evidence-record-contract.v1.json",
    "knowledge-hub.paper.parsed-artifact-strict-evidence-record.v1": "paper-parsed-artifact-strict-evidence-record.v1.json",
    "knowledge-hub.paper.parsed-artifact-strict-evidence-executor-dry-run.v1": "paper-parsed-artifact-strict-evidence-executor-dry-run.v1.json",
    "knowledge-hub.paper.parsed-artifact-strict-evidence-normalization-hash-repair.v1": "paper-parsed-artifact-strict-evidence-normalization-hash-repair.v1.json",
    "knowledge-hub.paper.parsed-artifact-strict-evidence-executor-apply.v1": "paper-parsed-artifact-strict-evidence-executor-apply.v1.json",
    "knowledge-hub.paper.parsed-artifact-strict-evidence-promotion-readback-review.v1": "paper-parsed-artifact-strict-evidence-promotion-readback-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-strict-evidence-policy-gate.v1": "paper-parsed-artifact-strict-evidence-policy-gate.v1.json",
    "knowledge-hub.paper.parsed-artifact-strict-evidence-promotion-tranche-plan.v1": "paper-parsed-artifact-strict-evidence-promotion-tranche-plan.v1.json",
    "knowledge-hub.paper.strict-evidence-text-section-pilot.v1": "paper-strict-evidence-text-section-pilot.v1.json",
    "knowledge-hub.paper.strict-evidence-text-section-pilot-executor-dry-run.v1": "paper-strict-evidence-text-section-pilot-executor-dry-run.v1.json",
    "knowledge-hub.paper.strict-evidence-text-section-pilot-executor-apply.v1": "paper-strict-evidence-text-section-pilot-executor-apply.v1.json",
    "knowledge-hub.paper.strict-evidence-figure-caption-pilot.v1": "paper-strict-evidence-figure-caption-pilot.v1.json",
    "knowledge-hub.paper.strict-evidence-figure-caption-pilot-executor-dry-run.v1": "paper-strict-evidence-figure-caption-pilot-executor-dry-run.v1.json",
    "knowledge-hub.paper.strict-evidence-figure-caption-pilot-executor-apply.v1": "paper-strict-evidence-figure-caption-pilot-executor-apply.v1.json",
    "knowledge-hub.paper.strict-evidence-pilot-tranche-manifest-readback-review.v1": "paper-strict-evidence-pilot-tranche-manifest-readback-review.v1.json",
    "knowledge-hub.paper.strict-evidence-pilot-tranche-completion-gate.v1": "paper-strict-evidence-pilot-tranche-completion-gate.v1.json",
    "knowledge-hub.paper.strict-evidence-post-pilot-promotion-hold-review.v1": "paper-strict-evidence-post-pilot-promotion-hold-review.v1.json",
    "knowledge-hub.paper.strict-evidence-strict-eligible-mutation-decision-record.v1": "paper-strict-evidence-strict-eligible-mutation-decision-record.v1.json",
    "knowledge-hub.paper.strict-evidence-eligibility-record-contract.v1": "paper-strict-evidence-eligibility-record-contract.v1.json",
    "knowledge-hub.paper.strict-evidence-eligibility-record.v1": "paper-strict-evidence-eligibility-record.v1.json",
    "knowledge-hub.paper.strict-evidence-eligibility-executor-dry-run.v1": "paper-strict-evidence-eligibility-executor-dry-run.v1.json",
    "knowledge-hub.paper.strict-evidence-eligibility-executor-apply.v1": "paper-strict-evidence-eligibility-executor-apply.v1.json",
    "knowledge-hub.paper.strict-evidence-eligibility-executor-apply-readback-review.v1": "paper-strict-evidence-eligibility-executor-apply-readback-review.v1.json",
    "knowledge-hub.paper.strict-evidence-eligibility-post-apply-promotion-hold-review.v1": "paper-strict-evidence-eligibility-post-apply-promotion-hold-review.v1.json",
    "knowledge-hub.paper.strict-evidence-citation-grade-policy-gate-design.v1": "paper-strict-evidence-citation-grade-policy-gate-design.v1.json",
    "knowledge-hub.paper.strict-evidence-citation-grade-record-contract.v1": "paper-strict-evidence-citation-grade-record-contract.v1.json",
    "knowledge-hub.paper.strict-evidence-citation-grade-record.v1": "paper-strict-evidence-citation-grade-record.v1.json",
    "knowledge-hub.paper.strict-evidence-citation-grade-executor-dry-run.v1": "paper-strict-evidence-citation-grade-executor-dry-run.v1.json",
    "knowledge-hub.paper.strict-evidence-citation-grade-executor-apply.v1": "paper-strict-evidence-citation-grade-executor-apply.v1.json",
    "knowledge-hub.paper.strict-evidence-citation-grade-executor-apply-readback-review.v1": "paper-strict-evidence-citation-grade-executor-apply-readback-review.v1.json",
    "knowledge-hub.paper.strict-evidence-citation-grade-post-apply-promotion-hold-review.v1": "paper-strict-evidence-citation-grade-post-apply-promotion-hold-review.v1.json",
    "knowledge-hub.paper.strict-evidence-citation-grade-runtime-binding-gate-design.v1": "paper-strict-evidence-citation-grade-runtime-binding-gate-design.v1.json",
    "knowledge-hub.paper.strict-evidence-runtime-binding-record-contract.v1": "paper-strict-evidence-runtime-binding-record-contract.v1.json",
    "knowledge-hub.paper.strict-evidence-runtime-binding-record.v1": "paper-strict-evidence-runtime-binding-record.v1.json",
    "knowledge-hub.paper.strict-evidence-runtime-binding-executor-dry-run.v1": "paper-strict-evidence-runtime-binding-executor-dry-run.v1.json",
    "knowledge-hub.paper.strict-evidence-runtime-binding-executor-apply.v1": "paper-strict-evidence-runtime-binding-executor-apply.v1.json",
    "knowledge-hub.paper.strict-evidence-runtime-binding-executor-apply-readback-review.v1": "paper-strict-evidence-runtime-binding-executor-apply-readback-review.v1.json",
    "knowledge-hub.paper.strict-evidence-runtime-binding-post-apply-promotion-hold-review.v1": "paper-strict-evidence-runtime-binding-post-apply-promotion-hold-review.v1.json",
    "knowledge-hub.paper.strict-evidence-runtime-binding-visibility-decision-record.v1": "paper-strict-evidence-runtime-binding-visibility-decision-record.v1.json",
    "knowledge-hub.paper.strict-evidence-runtime-binding-visibility-record-contract.v1": "paper-strict-evidence-runtime-binding-visibility-record-contract.v1.json",
    "knowledge-hub.paper.strict-evidence-runtime-binding-visibility-record.v1": "paper-strict-evidence-runtime-binding-visibility-record.v1.json",
    "knowledge-hub.paper.tex-equation-quote-candidate-v2-design.v1": "paper-tex-equation-quote-candidate-v2-design.v1.json",
    "knowledge-hub.paper.tex-equation-remaining-window-diagnostic.v1": "paper-tex-equation-remaining-window-diagnostic.v1.json",
    "knowledge-hub.paper.tex-equation-segmented-multiline-matching-design.v1": "paper-tex-equation-segmented-multiline-matching-design.v1.json",
    "knowledge-hub.paper.tex-equation-rendered-macro-term-profile-design.v1": "paper-tex-equation-rendered-macro-term-profile-design.v1.json",
    "knowledge-hub.paper.tex-equation-label-number-pdf-region-disambiguation-design.v1": "paper-tex-equation-label-number-pdf-region-disambiguation-design.v1.json",
    "knowledge-hub.paper.tex-equation-source-span-promotion-readiness-audit.v1": "paper-tex-equation-source-span-promotion-readiness-audit.v1.json",
    "knowledge-hub.paper.equation-authority-readiness-audit.v1": "paper-equation-authority-readiness-audit.v1.json",
    "knowledge-hub.paper.equation-authority-hash-identity-design.v1": "paper-equation-authority-hash-identity-design.v1.json",
    "knowledge-hub.paper.equation-authority-contract-design.v1": "paper-equation-authority-contract-design.v1.json",
    "knowledge-hub.paper.equation-authority-record-contract.v1": "paper-equation-authority-record-contract.v1.json",
    "knowledge-hub.paper.equation-authority-record.v1": "paper-equation-authority-record.v1.json",
    "knowledge-hub.paper.equation-authority-record-executor-dry-run.v1": "paper-equation-authority-record-executor-dry-run.v1.json",
    "knowledge-hub.paper.equation-authority-record-executor-apply.v1": "paper-equation-authority-record-executor-apply.v1.json",
    "knowledge-hub.paper.mineru-normalizer-audit.v1": "paper-mineru-normalizer-audit.v1.json",
    "knowledge-hub.paper.mineru-source-alignment-audit.v1": "paper-mineru-source-alignment-audit.v1.json",
    "knowledge-hub.paper.mineru-potential-review-pack.v1": "paper-mineru-potential-review-pack.v1.json",
    "knowledge-hub.paper.sectionspan-candidate-report.v1": "paper-sectionspan-candidate-report.v1.json",
    "knowledge-hub.paper.figure-caption-candidate-report.v1": "paper-figure-caption-candidate-report.v1.json",
    "knowledge-hub.paper.equation-quote-candidate-report.v1": "paper-equation-quote-candidate-report.v1.json",
    "knowledge-hub.paper.table-region-candidate-report.v1": "paper-table-region-candidate-report.v1.json",
    "knowledge-hub.paper.structured-candidate-summary.v1": "paper-structured-candidate-summary.v1.json",
    "knowledge-hub.paper.parsed-artifact-structured-evidence-readiness-audit.v1": "paper-parsed-artifact-structured-evidence-readiness-audit.v1.json",
    "knowledge-hub.paper.complex-qa-eval-design.v1": "paper-complex-qa-eval-design.v1.json",
    "knowledge-hub.paper.complex-qa-seed-pack.v1": "paper-complex-qa-seed-pack.v1.json",
    "knowledge-hub.paper.corpus-manifest-validation.v1": "paper-corpus-manifest-validation.v1.json",
    "knowledge-hub.paper.corpus-source-artifact-inventory.v1": "paper-corpus-source-artifact-inventory.v1.json",
    "knowledge-hub.corpus-manifest-expansion-tranche-plan.v1": "corpus-manifest-expansion-tranche-plan.v1.json",
    "knowledge-hub.priority-corpus-candidate-ledger.v1": "priority-corpus-candidate-ledger.v1.json",
    "knowledge-hub.priority-corpus-source-join-report.v1": "priority-corpus-source-join-report.v1.json",
    "knowledge-hub.priority-corpus-manifest-expansion-allowlist.v1": "priority-corpus-manifest-expansion-allowlist.v1.json",
    "knowledge-hub.priority-corpus-300-freeze-report.v1": "priority-corpus-300-freeze-report.v1.json",
    "knowledge-hub.paper.structured-evidence-vertical-slice-discovery.v1": "paper-structured-evidence-vertical-slice-discovery.v1.json",
    "knowledge-hub.paper.structured-evidence-vertical-slice-implementation.v1": "paper-structured-evidence-vertical-slice-implementation.v1.json",
    "knowledge-hub.paper.structured-evidence-next-slice-candidate-report.v1": "paper-structured-evidence-next-slice-candidate-report.v1.json",
    "knowledge-hub.paper.structured-evidence-next-slice-apply-readback.v1": "paper-structured-evidence-next-slice-apply-readback.v1.json",
    "knowledge-hub.paper.runtime-answer-integration-gap-report.v1": "paper-runtime-answer-integration-gap-report.v1.json",
    "knowledge-hub.paper.visual-layout-candidate-list-report.v1": "paper-visual-layout-candidate-list-report.v1.json",
    "knowledge-hub.paper.visual-annotation-web-pack.v1": "paper-visual-annotation-web-pack.v1.json",
    "knowledge-hub.paper.visual-annotation-attachment-pack.v1": "paper-visual-annotation-attachment-pack.v1.json",
    "knowledge-hub.paper.visual-annotation-web-output.v1": "paper-visual-annotation-web-output.v1.json",
    "knowledge-hub.paper.visual-annotation-web-output-validation.v1": "paper-visual-annotation-web-output-validation.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-candidate-store-design.v1": "paper-visual-retrieval-hint-candidate-store-design.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-candidate-store-dry-run.v1": "paper-visual-retrieval-hint-candidate-store-dry-run.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-candidate-store-expansion-design.v1": "paper-visual-retrieval-hint-candidate-store-expansion-design.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-candidate-store-expansion-dry-run.v1": "paper-visual-retrieval-hint-candidate-store-expansion-dry-run.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-candidate-store-expansion-review.v1": "paper-visual-retrieval-hint-candidate-store-expansion-review.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-candidate-store-expansion-human-product-decision-record.v1": "paper-visual-retrieval-hint-candidate-store-expansion-human-product-decision-record.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-candidate-store-expansion-gpt-decision-review-pack.v1": "paper-visual-retrieval-hint-candidate-store-expansion-gpt-decision-review-pack.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-candidate-store-expansion-gpt-recommendation-output-validation.v1": "paper-visual-retrieval-hint-candidate-store-expansion-gpt-recommendation-output-validation.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-usefulness-eval.v1": "paper-visual-retrieval-hint-usefulness-eval.v1.json",
    "knowledge-hub.paper.visual-retrieval-hint-search-eval.v1": "paper-visual-retrieval-hint-search-eval.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-apply-design.v1": "paper-limited-visual-retrieval-hint-candidate-store-apply-design.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-apply-review.v1": "paper-limited-visual-retrieval-hint-candidate-store-apply-review.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-apply-allowlist-review.v1": "paper-limited-visual-retrieval-hint-candidate-store-apply-allowlist-review.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-allowlist-apply-executor-dry-run.v1": "paper-limited-visual-retrieval-hint-candidate-store-allowlist-apply-executor-dry-run.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-apply-executor.v1": "paper-limited-visual-retrieval-hint-candidate-store-apply-executor.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-apply-readback-review.v1": "paper-limited-visual-retrieval-hint-candidate-store-apply-readback-review.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-labs-vector-index-dry-run.v1": "paper-limited-visual-retrieval-hint-candidate-store-labs-vector-index-dry-run.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-labs-vector-index-review.v1": "paper-limited-visual-retrieval-hint-candidate-store-labs-vector-index-review.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-labs-vector-index-apply-executor-dry-run.v1": "paper-limited-visual-retrieval-hint-candidate-store-labs-vector-index-apply-executor-dry-run.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-labs-vector-index-apply-review.v1": "paper-limited-visual-retrieval-hint-candidate-store-labs-vector-index-apply-review.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-labs-vector-index-apply-executor.v1": "paper-limited-visual-retrieval-hint-candidate-store-labs-vector-index-apply-executor.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-candidate-store-labs-vector-index-search-quality-eval.v1": "paper-limited-visual-retrieval-hint-candidate-store-labs-vector-index-search-quality-eval.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-production-vector-db-integration-design.v1": "paper-limited-visual-retrieval-hint-production-vector-db-integration-design.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-production-vector-db-integration-dry-run.v1": "paper-limited-visual-retrieval-hint-production-vector-db-integration-dry-run.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-production-vector-db-integration-apply-executor.v1": "paper-limited-visual-retrieval-hint-production-vector-db-integration-apply-executor.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-production-vector-db-search-quality-eval.v1": "paper-limited-visual-retrieval-hint-production-vector-db-search-quality-eval.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-runtime-candidate-discovery-route-design.v1": "paper-limited-visual-retrieval-hint-runtime-candidate-discovery-route-design.v1.json",
    "knowledge-hub.paper.limited-visual-retrieval-hint-final-merge-review.v1": "paper-limited-visual-retrieval-hint-final-merge-review.v1.json",
    "knowledge-hub.paper.paper-retrieval-lane-split-parsed-artifact-evidence-chunk-dry-run.v1": "paper-retrieval-lane-split-parsed-artifact-evidence-chunk-dry-run.v1.json",
    "knowledge-hub.paper.paper-retrieval-lane-split-parsed-artifact-evidence-chunk-contract-review.v1": "paper-retrieval-lane-split-parsed-artifact-evidence-chunk-contract-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-dry-run.v1": "paper-parsed-artifact-evidence-chunk-candidate-dry-run.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-canary-apply-readback.v1": "paper-parsed-artifact-evidence-chunk-candidate-canary-apply-readback.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-full-apply-readiness-gate.v1": "paper-parsed-artifact-evidence-chunk-candidate-full-apply-readiness-gate.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-full-apply-executor-apply-readback.v1": "paper-parsed-artifact-evidence-chunk-candidate-full-apply-executor-apply-readback.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-full-apply-readback-review.v1": "paper-parsed-artifact-evidence-chunk-candidate-full-apply-readback-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-answerability-policy-gate.v1": "paper-parsed-artifact-evidence-chunk-candidate-answerability-policy-gate.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-runtime-integration-dry-run.v1": "paper-parsed-artifact-evidence-chunk-candidate-runtime-integration-dry-run.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-runtime-contract-review.v1": "paper-parsed-artifact-evidence-chunk-candidate-runtime-contract-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-runtime-adapter-design.v1": "paper-parsed-artifact-evidence-chunk-candidate-runtime-adapter-design.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-candidate-runtime-adapter-dry-run.v1": "paper-parsed-artifact-evidence-chunk-candidate-runtime-adapter-dry-run.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-runtime-adapter-live-smoke.v1": "paper-parsed-artifact-evidence-chunk-runtime-adapter-live-smoke.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-real-answer-quality-smoke.v1": "paper-parsed-artifact-evidence-chunk-real-answer-quality-smoke.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-opt-in-route-review.v1": "paper-parsed-artifact-evidence-chunk-answer-path-opt-in-route-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-opt-in-implementation-design.v1": "paper-parsed-artifact-evidence-chunk-answer-path-opt-in-implementation-design.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-searcher-ingress-live-smoke.v1": "paper-parsed-artifact-evidence-chunk-answer-path-searcher-ingress-live-smoke.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-default-off-no-answer-regression-smoke.v1": "paper-parsed-artifact-evidence-chunk-answer-path-default-off-no-answer-regression-smoke.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-labs-opt-in-surface-design.v1": "paper-parsed-artifact-evidence-chunk-answer-path-labs-opt-in-surface-design.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-labs-opt-in-surface-live-smoke.v1": "paper-parsed-artifact-evidence-chunk-answer-path-labs-opt-in-surface-live-smoke.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-labs-opt-in-quality-eval-seed.v1": "paper-parsed-artifact-evidence-chunk-answer-path-labs-opt-in-quality-eval-seed.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-labs-opt-in-quality-eval-runner.v1": "paper-parsed-artifact-evidence-chunk-answer-path-labs-opt-in-quality-eval-runner.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-labs-opt-in-user-test-packet.v1": "paper-parsed-artifact-evidence-chunk-answer-path-labs-opt-in-user-test-packet.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-labs-opt-in-user-test-output-capture.v1": "paper-parsed-artifact-evidence-chunk-answer-path-labs-opt-in-user-test-output-capture.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-labs-opt-in-user-test-promotion-review.v1": "paper-parsed-artifact-evidence-chunk-answer-path-labs-opt-in-user-test-promotion-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-v01-rc-labs-release-gate.v1": "paper-parsed-artifact-evidence-chunk-answer-path-v01-rc-labs-release-gate.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-v01-rc-branch-pr-readiness-review.v1": "paper-parsed-artifact-evidence-chunk-answer-path-v01-rc-branch-pr-readiness-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-v01-rc-draft-pr-opening-or-handoff.v1": "paper-parsed-artifact-evidence-chunk-answer-path-v01-rc-draft-pr-opening-or-handoff.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-v01-rc-post-merge-convergence.v1": "paper-parsed-artifact-evidence-chunk-answer-path-v01-rc-post-merge-convergence.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-v01-rc-public-default-promotion-decision-gate.v1": "paper-parsed-artifact-evidence-chunk-answer-path-v01-rc-public-default-promotion-decision-gate.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-v01-rc-research-preview-release-notes-review.v1": "paper-parsed-artifact-evidence-chunk-answer-path-v01-rc-research-preview-release-notes-review.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-v01-rc-release-package-handoff.v1": "paper-parsed-artifact-evidence-chunk-answer-path-v01-rc-release-package-handoff.v1.json",
    "knowledge-hub.paper.parsed-artifact-evidence-chunk-answer-path-v01-rc-draft-pr-post-open-review.v1": "paper-parsed-artifact-evidence-chunk-answer-path-v01-rc-draft-pr-post-open-review.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-vision-bottleneck-definition-review.v1": "knowledgeos-v01-rc-vision-bottleneck-definition-review.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-post-merge-convergence-cleanup-decision.v1": "knowledgeos-v01-rc-post-merge-convergence-cleanup-decision.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-corpus-scale-answer-quality-gate.v1": "knowledgeos-v01-rc-corpus-scale-answer-quality-gate.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-corpus-scale-answer-quality-live-runner-design.v1": "knowledgeos-v01-rc-corpus-scale-answer-quality-live-runner-design.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-corpus-scale-answer-quality-live-runner-dry-run.v1": "knowledgeos-v01-rc-corpus-scale-answer-quality-live-runner-dry-run.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-corpus-scale-answer-quality-controlled-execution.v1": "knowledgeos-v01-rc-corpus-scale-answer-quality-controlled-execution.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-corpus-scale-controlled-execution-post-merge-convergence.v1": "knowledgeos-v01-rc-corpus-scale-controlled-execution-post-merge-convergence.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-answerability-gate-repair-post-merge-convergence.v1": "knowledgeos-v01-rc-answerability-gate-repair-post-merge-convergence.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-corpus-scale-answer-quality-positive-section-paragraph-seed.v1": "knowledgeos-v01-rc-corpus-scale-answer-quality-positive-section-paragraph-seed.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-corpus-scale-answer-quality-positive-answer-execution-gate.v1": "knowledgeos-v01-rc-corpus-scale-answer-quality-positive-answer-execution-gate.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-corpus-scale-answer-quality-gate-refresh-after-positive-answer-execution.v1": "knowledgeos-v01-rc-corpus-scale-answer-quality-gate-refresh-after-positive-answer-execution.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-positive-section-paragraph-quality-complete-review.v1": "knowledgeos-v01-rc-positive-section-paragraph-quality-complete-review.v1.json",
    "knowledge-hub.product.knowledgeos-v01-rc-research-preview-release-readiness-decision-gate.v1": "knowledgeos-v01-rc-research-preview-release-readiness-decision-gate.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-pack-design.v1": "paper-visual-annotation-expansion-pack-design.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-attachment-pack.v1": "paper-visual-annotation-expansion-attachment-pack.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-manual-run-packet.v1": "paper-visual-annotation-expansion-manual-run-packet.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-web-output-validation.v1": "paper-visual-annotation-expansion-web-output-validation.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-operator-handoff.v1": "paper-visual-annotation-expansion-operator-handoff.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-web-output-template.v1": "paper-visual-annotation-expansion-web-output-template.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-web-run-bundle.v1": "paper-visual-annotation-expansion-web-run-bundle.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-web-run-batch-template.v1": "paper-visual-annotation-expansion-web-run-batch-template.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-web-upload-bundle.v1": "paper-visual-annotation-expansion-web-upload-bundle.v1.json",
    "knowledge-hub.paper.visual-annotation-expansion-web-batch-output-collector.v1": "paper-visual-annotation-expansion-web-batch-output-collector.v1.json",
    "knowledge-hub.paper.complex-qa-abstain-baseline-runner.v1": "paper-complex-qa-abstain-baseline-runner.v1.json",
    "knowledge-hub.paper.complex-qa-structured-evidence-comparison-runner.v1": "paper-complex-qa-structured-evidence-comparison-runner.v1.json",
    "knowledge-hub.paper.complex-qa-strict-evidence-answer-quality-dry-run.v1": "paper-complex-qa-strict-evidence-answer-quality-dry-run.v1.json",
    "knowledge-hub.paper.complex-qa-strict-evidence-answer-quality-grader-design.v1": "paper-complex-qa-strict-evidence-answer-quality-grader-design.v1.json",
    "knowledge-hub.paper.complex-qa-supplied-strict-evidence-synthetic-grading-fixture-runner.v1": "paper-complex-qa-supplied-strict-evidence-synthetic-grading-fixture-runner.v1.json",
    "knowledge-hub.paper.complex-qa-supplied-strict-evidence-grader-baseline-runner.v1": "paper-complex-qa-supplied-strict-evidence-grader-baseline-runner.v1.json",
    "knowledge-hub.paper.candidate-layer-review-gate.v1": "paper-candidate-layer-review-gate.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-backlog.v1": "paper-candidate-layer-blocker-backlog.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-review-pack.v1": "paper-candidate-layer-blocker-review-pack.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-decision-template.v1": "paper-candidate-layer-blocker-decision-template.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-decision-record.v1": "paper-candidate-layer-blocker-decision-record.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-decision-input-pack.v1": "paper-candidate-layer-blocker-decision-input-pack.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-decision-edit-plan.v1": "paper-candidate-layer-blocker-decision-edit-plan.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-decision-file-validation.v1": "paper-candidate-layer-blocker-decision-file-validation.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-decision-file-draft.v1": "paper-candidate-layer-blocker-decision-file-draft.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-manual-decision-review-sheet.v1": "paper-candidate-layer-blocker-manual-decision-review-sheet.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-manual-decision-command-packet.v1": "paper-candidate-layer-blocker-manual-decision-command-packet.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-nonbinding-decision-recommendations.v1": "paper-candidate-layer-blocker-nonbinding-decision-recommendations.v1.json",
    "knowledge-hub.paper.candidate-layer-blocker-resolution-preview.v1": "paper-candidate-layer-blocker-resolution-preview.v1.json",
    "knowledge-hub.paper.candidate-layer-remaining-manual-blocker-review-pack.v1": "paper-candidate-layer-remaining-manual-blocker-review-pack.v1.json",
    "knowledge-hub.paper.non-sectionspan-pdf-offset-feasibility-audit.v1": "paper-non-sectionspan-pdf-offset-feasibility-audit.v1.json",
    "knowledge-hub.paper.source-span-offset-authority-audit.v1": "paper-source-span-offset-authority-audit.v1.json",
    "knowledge-hub.paper.equation-alignment-feasibility-audit.v1": "paper-equation-alignment-feasibility-audit.v1.json",
    "knowledge-hub.paper.equation-quote-next-action-gate.v1": "paper-equation-quote-next-action-gate.v1.json",
    "knowledge-hub.paper.equation-quote-manual-review-sheet.v1": "paper-equation-quote-manual-review-sheet.v1.json",
    "knowledge-hub.paper.equation-quote-decision-file-draft.v1": "paper-equation-quote-decision-file-draft.v1.json",
    "knowledge-hub.paper.equation-quote-decision-file-validation.v1": "paper-equation-quote-decision-file-validation.v1.json",
    "knowledge-hub.paper.equation-quote-decision-record.v1": "paper-equation-quote-decision-record.v1.json",
    "knowledge-hub.paper.equation-quote-decision-next-action-brief.v1": "paper-equation-quote-decision-next-action-brief.v1.json",
    "knowledge-hub.paper.equation-quote-decision-recommendation-pack.v1": "paper-equation-quote-decision-recommendation-pack.v1.json",
    "knowledge-hub.paper.equation-quote-decision-edit-plan.v1": "paper-equation-quote-decision-edit-plan.v1.json",
    "knowledge-hub.paper.table-cell-provenance-feasibility-audit.v1": "paper-table-cell-provenance-feasibility-audit.v1.json",
    "knowledge-hub.paper.figure-region-link-feasibility-audit.v1": "paper-figure-region-link-feasibility-audit.v1.json",
    "knowledge-hub.paper.candidate-layer-promotion-policy-draft.v1": "paper-candidate-layer-promotion-policy-draft.v1.json",
    "knowledge-hub.paper.sectionspan-contract-review.v1": "paper-sectionspan-contract-review.v1.json",
    "knowledge-hub.paper.sectionspan-contract-review-pack.v1": "paper-sectionspan-contract-review-pack.v1.json",
    "knowledge-hub.paper.sectionspan-strict-promotion-design.v1": "paper-sectionspan-strict-promotion-design.v1.json",
    "knowledge-hub.paper.sectionspan-source-authority-options.v1": "paper-sectionspan-source-authority-options.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-recovery-design.v1": "paper-sectionspan-pdf-offset-recovery-design.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-recovery-dry-run.v1": "paper-sectionspan-pdf-offset-recovery-dry-run.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-recovery-review-pack.v1": "paper-sectionspan-pdf-offset-recovery-review-pack.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-human-review-gate.v1": "paper-sectionspan-pdf-offset-human-review-gate.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-review-decision-template.v1": "paper-sectionspan-pdf-offset-review-decision-template.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-review-decision-record.v1": "paper-sectionspan-pdf-offset-review-decision-record.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-review-priority-pack.v1": "paper-sectionspan-pdf-offset-review-priority-pack.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-selected-review-packet.v1": "paper-sectionspan-pdf-offset-selected-review-packet.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-selected-review-decision-template.v1": "paper-sectionspan-pdf-offset-selected-review-decision-template.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-selected-review-decision-file-draft.v1": "paper-sectionspan-pdf-offset-selected-review-decision-file-draft.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-selected-review-decision-file-validation.v1": "paper-sectionspan-pdf-offset-selected-review-decision-file-validation.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-selected-review-manual-sheet.v1": "paper-sectionspan-pdf-offset-selected-review-manual-sheet.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-selected-review-next-action-brief.v1": "paper-sectionspan-pdf-offset-selected-review-next-action-brief.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-selected-review-decision-record.v1": "paper-sectionspan-pdf-offset-selected-review-decision-record.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-selected-review-evidence-pack.v1": "paper-sectionspan-pdf-offset-selected-review-evidence-pack.v1.json",
    "knowledge-hub.paper.sectionspan-pdf-offset-selected-review-decision-proposal.v1": "paper-sectionspan-pdf-offset-selected-review-decision-proposal.v1.json",
    "knowledge-hub.paper.figure-caption-pdf-offset-feasibility.v1": "paper-figure-caption-pdf-offset-feasibility.v1.json",
    "knowledge-hub.paper.figure-caption-region-link-review-pack.v1": "paper-figure-caption-region-link-review-pack.v1.json",
    "knowledge-hub.paper.equation-quote-pdf-offset-feasibility.v1": "paper-equation-quote-pdf-offset-feasibility.v1.json",
    "knowledge-hub.paper.table-region-pdf-offset-feasibility.v1": "paper-table-region-pdf-offset-feasibility.v1.json",
    "knowledge-hub.paper.table-cell-provenance-review-pack.v1": "paper-table-cell-provenance-review-pack.v1.json",
    "knowledge-hub.paper.table-cell-bbox-source-span-authority-design.v1": "paper-table-cell-bbox-source-span-authority-design.v1.json",
    "knowledge-hub.paper.table-cell-bbox-source-span-extractor-pilot.v1": "paper-table-cell-bbox-source-span-extractor-pilot.v1.json",
    "knowledge-hub.paper.table-cell-probe-result-review-pack.v1": "paper-table-cell-probe-result-review-pack.v1.json",
    "knowledge-hub.paper.table-cell-pymupdf-overlay-review-pack.v1": "paper-table-cell-pymupdf-overlay-review-pack.v1.json",
    "knowledge-hub.paper.table-cell-pymupdf-pairing-diagnostic.v1": "paper-table-cell-pymupdf-pairing-diagnostic.v1.json",
    "knowledge-hub.paper.table-cell-next-action-gate.v1": "paper-table-cell-next-action-gate.v1.json",
    "knowledge-hub.paper.table-cell-structured-evidence-readiness-audit.v1": "paper-table-cell-structured-evidence-readiness-audit.v1.json",
    "knowledge-hub.paper.table-cell-isolated-extractor-pilot-plan.v1": "paper-table-cell-isolated-extractor-pilot-plan.v1.json",
    "knowledge-hub.paper.table-cell-isolated-extractor-pilot-result.v1": "paper-table-cell-isolated-extractor-pilot-result.v1.json",
    "knowledge-hub.paper.canon-quality-audit.result.v1": "paper-canon-quality-audit-result.v1.json",
    "knowledge-hub.paper.board-export.v1": "paper-board-export-result.v1.json",
    "knowledge-hub.paper-memory.build.result.v1": "paper-memory-build-result.v1.json",
    "knowledge-hub.paper-memory.card.result.v1": "paper-memory-card-result.v1.json",
    "knowledge-hub.paper-memory.search.result.v1": "paper-memory-search-result.v1.json",
    "knowledge-hub.paper-knowledge-slots.v1": "paper-knowledge-slots.v1.json",
    "knowledge-hub.paper-topic-synthesis.result.v1": "paper-topic-synthesis-result.v1.json",
    "knowledge-hub.paper-memory.eval.report.v1": "paper-memory-eval-report.v1.json",
    "knowledge-hub.paper-topic-synthesis.result.v1": "paper-topic-synthesis-result.v1.json",
    "knowledge-hub.claim-normalize.result.v1": "claim-normalize-result.v1.json",
    "knowledge-hub.claim-compare.result.v1": "claim-compare-result.v1.json",
    "knowledge-hub.claim-synthesis.result.v1": "claim-synthesis-result.v1.json",
    "knowledge-hub.ai-watchlist-batch.v2": "ai-watchlist-batch.v2.json",
    "knowledge-hub.foundry.agent.run.result.v1": "agent-run-result.v1.json",
    "knowledge-hub.agent.writeback.request.result.v1": "agent-writeback-request-result.v1.json",
    "knowledge-hub.agent.discover.result.v1": "agent-discover-result.v1.json",
    "knowledge-hub.foundry.connector.sync.result.v2": "connector-sync-result.v2.json",
    "knowledge-hub.authority.result-envelope.v1": "authority-result-envelope.v1.json",
    "knowledge-hub.learning.map.result.v1": "learning-map-result.v1.json",
    "knowledge-hub.learning.start-resume.result.v1": "learning-start-resume-result.v1.json",
    "knowledge-hub.learning.session-state.result.v1": "learning-session-state-result.v1.json",
    "knowledge-hub.learning.explain.result.v1": "learning-explain-result.v1.json",
    "knowledge-hub.learning.checkpoint.result.v1": "learning-checkpoint-result.v1.json",
    "knowledge-hub.learning.grade.result.v1": "learning-grade-result.v1.json",
    "knowledge-hub.learning.next.result.v1": "learning-next-result.v1.json",
    "knowledge-hub.learning.template.result.v1": "learning-template-result.v1.json",
    "knowledge-hub.learning.run.result.v1": "learning-run-result.v1.json",
    "knowledge-hub.learning.gap.result.v1": "learning-gap-result.v1.json",
    "knowledge-hub.learning.quiz.generate.result.v1": "learning-quiz-generate-result.v1.json",
    "knowledge-hub.learning.quiz.grade.result.v1": "learning-quiz-grade-result.v1.json",
    "knowledge-hub.learning.patch.suggest.result.v1": "learning-patch-suggest-result.v1.json",
    "knowledge-hub.learning.reinforcement.result.v1": "learning-reinforcement-result.v1.json",
    "knowledge-hub.learning.graph.build.result.v1": "learning-graph-build-result.v1.json",
    "knowledge-hub.learning.graph.pending.result.v1": "learning-graph-pending-result.v1.json",
    "knowledge-hub.learning.path.result.v1": "learning-path-result.v1.json",
    "knowledge-hub.learning.review.result.v1": "learning-review-result.v1.json",
    "knowledge-hub.crawl.ingest.result.v1": "crawl-ingest-result.v1.json",
    "knowledge-hub.crawl.collect.result.v1": "crawl-collect-result.v1.json",
    "knowledge-hub.dinger.ingest.result.v1": "dinger-ingest-result.v1.json",
    "knowledge-hub.dinger.ask.result.v1": "dinger-ask-result.v1.json",
    "knowledge-hub.dinger.capture.result.v1": "dinger-capture-result.v1.json",
    "knowledge-hub.dinger.capture-list.result.v1": "dinger-capture-list-result.v1.json",
    "knowledge-hub.dinger.capture-status.result.v1": "dinger-capture-status-result.v1.json",
    "knowledge-hub.dinger.capture-show.result.v1": "dinger-capture-show-result.v1.json",
    "knowledge-hub.dinger.capture-process.result.v1": "dinger-capture-process-result.v1.json",
    "knowledge-hub.dinger.capture-cleanup.result.v1": "dinger-capture-cleanup-result.v1.json",
    "knowledge-hub.dinger.capture-requeue.result.v1": "dinger-capture-requeue-result.v1.json",
    "knowledge-hub.dinger.capture-retry.result.v1": "dinger-capture-retry-result.v1.json",
    "knowledge-hub.dinger.file.result.v1": "dinger-file-result.v1.json",
    "knowledge-hub.dinger.recent.result.v1": "dinger-recent-result.v1.json",
    "knowledge-hub.dinger.lint.result.v1": "dinger-lint-result.v1.json",
    "knowledge-hub.normalized.web-record.v2": "normalized-web-record.v2.json",
    "knowledge-hub.indexed.web-record.v2": "indexed-web-record.v2.json",
    "knowledge-hub.prepared-source-record.v1": "prepared-source-record.v1.json",
    "knowledge-hub.source-ledger-record.v1": "source-ledger-record.v1.json",
    "knowledge-hub.crawl.pending.list.result.v1": "crawl-pending-list-result.v1.json",
    "knowledge-hub.crawl.pending.apply.result.v1": "crawl-pending-apply-result.v1.json",
    "knowledge-hub.crawl.pending.reject.result.v1": "crawl-pending-reject-result.v1.json",
    "knowledge-hub.crawl.pipeline.run.result.v1": "crawl-pipeline-run-result.v1.json",
    "knowledge-hub.crawl.domain.policy.result.v1": "crawl-domain-policy-result.v1.json",
    "knowledge-hub.crawl.benchmark.result.v1": "crawl-benchmark-result.v1.json",
    "knowledge-hub.entity.merge.list.result.v1": "entity-merge-list-result.v1.json",
    "knowledge-hub.entity.merge.apply.result.v1": "entity-merge-apply-result.v1.json",
    "knowledge-hub.entity.merge.reject.result.v1": "entity-merge-reject-result.v1.json",
    "knowledge-hub.ko-note.generate.result.v1": "ko-note-generate-result.v1.json",
    "knowledge-hub.ko-note.status.result.v1": "ko-note-status-result.v1.json",
    "knowledge-hub.ko-note.report.result.v1": "ko-note-report-result.v1.json",
    "knowledge-hub.ko-note.apply.result.v1": "ko-note-apply-result.v1.json",
    "knowledge-hub.ko-note.enrich.result.v1": "ko-note-enrich-result.v1.json",
    "knowledge-hub.ko-note.review.list.result.v1": "ko-note-review-list-result.v1.json",
    "knowledge-hub.ko-note.review.result.v1": "ko-note-review-result.v1.json",
    "knowledge-hub.ko-note.remediate.result.v1": "ko-note-remediate-result.v1.json",
    "knowledge-hub.rag.report.result.v1": "rag-report-result.v1.json",
    "knowledge-hub.rag.corrective-report.result.v1": "rag-corrective-report-result.v1.json",
    "knowledge-hub.rag.corrective-eval.report.v1": "rag-corrective-eval-report.v1.json",
    "knowledge-hub.rag.adaptive-plan.result.v1": "rag-adaptive-plan-result.v1.json",
    "knowledge-hub.rag.corrective-run.result.v1": "rag-corrective-run-result.v1.json",
    "knowledge-hub.rag.corrective-execution-review.result.v1": "rag-corrective-execution-review-result.v1.json",
    "knowledge-hub.rag.answerability-rerank.result.v1": "rag-answerability-rerank-result.v1.json",
    "knowledge-hub.rag.answerability-rerank-eval.report.v1": "rag-answerability-rerank-eval-report.v1.json",
    "knowledge-hub.rag.graph-global-plan.result.v1": "rag-graph-global-plan-result.v1.json",
    "knowledge-hub.rag.vnext-observation.report.v1": "rag-vnext-observation-report.v1.json",
    "knowledge-hub.rag.visualization.result.v1": "rag-visualization-result.v1.json",
    "knowledge-hub.runtime.diagnostics.v1": "runtime-diagnostics.v1.json",
    "knowledge-hub.doctor.result.v1": "doctor-result.v1.json",
    "knowledge-hub.retrieval.eval.report.v1": "retrieval-eval-report.v1.json",
    "knowledge-hub.eval.gate.result.v1": "eval-gate-result.v1.json",
    "knowledge-hub.answer-eval.packet.v1": "answer-eval-packet.v1.json",
    "knowledge-hub.answer-eval.result.v1": "answer-eval-result.v1.json",
    "knowledge-hub.evidence-packet.v1": "evidence-packet.v1.json",
    "knowledge-hub.answer-contract.v1": "answer-contract.v1.json",
    "knowledge-hub.verification-verdict.v1": "verification-verdict.v1.json",
    "knowledge-hub.compare-packet.v1": "compare-packet.v1.json",
    "knowledge-hub.evidence-substrate.contract.v1": "evidence-substrate-contract.v1.json",
    "knowledge-hub.inspect.result.v1": "inspect-result.v1.json",
    "knowledge-hub.compare.result.v1": "compare-result.v1.json",
    "knowledge-hub.answer-trace.result.v1": "answer-trace-result.v1.json",
    "knowledge-hub.mcp.resource.result.v1": "mcp-resource-result.v1.json",
    "knowledge-hub.evidence-registry.record.v1": "evidence-registry-record.v1.json",
    "knowledge-hub.evidence-registry.lookup.result.v1": "evidence-registry-lookup-result.v1.json",
    "knowledge-hub.evidence-registry.write.result.v1": "evidence-registry-write-result.v1.json",
    "knowledge-hub.answer-loop.collect.result.v1": "answer-loop-collect-result.v1.json",
    "knowledge-hub.answer-loop.judge.result.v1": "answer-loop-judge-result.v1.json",
    "knowledge-hub.answer-loop.summary.result.v1": "answer-loop-summary-result.v1.json",
    "knowledge-hub.answer-loop.autofix.result.v1": "answer-loop-autofix-result.v1.json",
    "knowledge-hub.answer-loop.run.result.v1": "answer-loop-run-result.v1.json",
    "knowledge-hub.answer-loop.optimize.result.v1": "answer-loop-optimize-result.v1.json",
    "knowledge-hub.ops.report.run.result.v1": "ops-report-run-result.v1.json",
    "knowledge-hub.ops.action.list.result.v1": "ops-action-list-result.v1.json",
    "knowledge-hub.ops.action.result.v1": "ops-action-result.v1.json",
    "knowledge-hub.ops.action.execute.result.v1": "ops-action-execute-result.v1.json",
    "knowledge-hub.ops.action.receipts.result.v1": "ops-action-receipts-result.v1.json",
    "knowledge-hub.ko-note.enrich.status.result.v1": "ko-note-enrich-status-result.v1.json",
    "knowledge-hub.vault.topology.snapshot.v1": "vault-topology-snapshot.v1.json",
    "knowledge-hub.vault.cluster.materialize.manifest.v1": "vault-cluster-materialize-manifest.v1.json",
    "knowledge-hub.task-context.result.v1": "task-context-result.v1.json",
    "knowledge-hub.context-pack.result.v1": "context-pack-result.v1.json",
    "knowledge-hub.eval-center.summary.result.v1": "eval-center-summary-result.v1.json",
    "knowledge-hub.eval-case.v1": "eval-case.v1.json",
    "knowledge-hub.eval-case-registry.result.v1": "eval-case-registry-result.v1.json",
    "knowledge-hub.failure-bank.sync.result.v1": "failure-bank-sync-result.v1.json",
    "knowledge-hub.failure-bank.list.result.v1": "failure-bank-list-result.v1.json",
    "knowledge-hub.failure-bank.link-eval-cases.result.v1": "failure-bank-link-eval-cases-result.v1.json",
    "knowledge-hub.os.project.create.result.v1": "os-project-create-result.v1.json",
    "knowledge-hub.os.project.list.result.v1": "os-project-list-result.v1.json",
    "knowledge-hub.os.project.update.result.v1": "os-project-update-result.v1.json",
    "knowledge-hub.os.project.show.result.v1": "os-project-show-result.v1.json",
    "knowledge-hub.os.project.evidence.result.v1": "os-project-evidence-result.v1.json",
    "knowledge-hub.os.evidence.show.result.v1": "os-evidence-show-result.v1.json",
    "knowledge-hub.os.evidence.review.result.v1": "os-evidence-review-result.v1.json",
    "knowledge-hub.os.capture.result.v1": "os-capture-result.v1.json",
    "knowledge-hub.os.goal.add.result.v1": "os-goal-add-result.v1.json",
    "knowledge-hub.os.goal.update.result.v1": "os-goal-update-result.v1.json",
    "knowledge-hub.os.task.add.result.v1": "os-task-add-result.v1.json",
    "knowledge-hub.os.task.update.result.v1": "os-task-update-result.v1.json",
    "knowledge-hub.os.task.update-status.result.v1": "os-task-update-status-result.v1.json",
    "knowledge-hub.os.task.start.result.v1": "os-task-start-result.v1.json",
    "knowledge-hub.os.task.block.result.v1": "os-task-block-result.v1.json",
    "knowledge-hub.os.task.complete.result.v1": "os-task-complete-result.v1.json",
    "knowledge-hub.os.task.cancel.result.v1": "os-task-cancel-result.v1.json",
    "knowledge-hub.os.inbox.triage.result.v1": "os-inbox-triage-result.v1.json",
    "knowledge-hub.os.decide.result.v1": "os-decide-result.v1.json",
    "knowledge-hub.os.decision.add.result.v1": "os-decision-add-result.v1.json",
    "knowledge-hub.os.decision.list.result.v1": "os-decision-list-result.v1.json",
    "knowledge-hub.os.inbox.list.result.v1": "os-inbox-list-result.v1.json",
    "knowledge-hub.os.inbox.resolve.result.v1": "os-inbox-resolve-result.v1.json",
    "knowledge-hub.os.next.result.v1": "os-next-result.v1.json",
    "knowledge-hub.os.project.export.obsidian.result.v1": "os-project-export-obsidian-result.v1.json",
    "knowledge-hub.notebook.provider.list.result.v1": "notebook-provider-list-result.v1.json",
    "knowledge-hub.notebook.provider.local-models.result.v1": "notebook-provider-local-models-result.v1.json",
    "knowledge-hub.notebook.topic.preview.result.v1": "notebook-topic-preview-result.v1.json",
    "knowledge-hub.notebook.topic.create.result.v1": "notebook-topic-create-result.v1.json",
    "knowledge-hub.notebook.topic.sync.result.v1": "notebook-topic-sync-result.v1.json",
    "knowledge-hub.transform.list.result.v1": "transform-list-result.v1.json",
    "knowledge-hub.transform.preview.result.v1": "transform-preview-result.v1.json",
    "knowledge-hub.transform.run.result.v1": "transform-run-result.v1.json",
    "knowledge-hub.ask-graph.result.v1": "ask-graph-result.v1.json",
    "knowledge-hub.workbench.search.result.v1": "workbench-search-result.v1.json",
    "knowledge-hub.workbench.chat.result.v1": "workbench-chat-result.v1.json",
    "knowledge-hub.paper.judge.result.v1": "paper-judge-result.v1.json",
    "knowledge-hub.paper.discover.result.v1": "paper-discover-result.v1.json",
}


@dataclass
class SchemaValidationResult:
    ok: bool
    errors: list[str]
    schema: str
    schema_found: bool


def _schema_file_for(schema_id: str) -> Path | None:
    file_name = SCHEMA_NAME_BY_ID.get(schema_id)
    if not file_name:
        return None
    candidate = SCHEMA_ROOT / file_name
    return candidate if candidate.exists() else None


def validate_payload(payload: dict[str, Any], schema_id: str, *, strict: bool = False) -> SchemaValidationResult:
    """Validate payload against registered JSON schema.

    Returns non-blocking validation failures by default (strict=False), so existing
    call sites can decide whether to escalate.
    """
    schema_path = _schema_file_for(schema_id)
    if schema_path is None:
        message = f"schema not found for id: {schema_id}"
        return SchemaValidationResult(ok=not strict, errors=[message], schema=schema_id, schema_found=False)

    return _validate_loaded(payload, schema_id, schema_path, strict=strict)


def _validate_loaded(payload: dict[str, Any], schema_id: str, schema_path: Path, strict: bool) -> SchemaValidationResult:
    try:
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
    except Exception as error:
        return SchemaValidationResult(
            ok=not strict,
            errors=[f"schema load failed: {schema_path}: {error}"],
            schema=schema_id,
            schema_found=False,
        )

    try:
        validator = Draft202012Validator(schema)
        def _format_path(error_path) -> str:
            parts = list(error_path)
            return "/" + "/".join(str(part) for part in parts) if parts else "(root)"

        errors = [f"{_format_path(item.path)}: {item.message}" for item in sorted(validator.iter_errors(payload), key=lambda item: item.path)]
    except Exception as error:
        return SchemaValidationResult(
            ok=not strict,
            errors=[f"schema validate failed: {error}"],
            schema=schema_id,
            schema_found=True,
        )

    return SchemaValidationResult(ok=(not errors or not strict), errors=errors, schema=schema_id, schema_found=True)


def annotate_schema_errors(payload: dict[str, Any], schema_id: str, *, strict: bool = False) -> SchemaValidationResult:
    result = validate_payload(payload, schema_id, strict=strict)
    if result.errors:
        existing = list(payload.get("schemaErrors", []))
        for error in result.errors:
            if error not in existing:
                existing.append(error)
        payload["schemaErrors"] = existing
    return result
